version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: psy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgr  esql/data
    ports:
    - 5432:5432
