# Generated by Django 4.2.3 on 2023-07-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_lastname', models.CharField(max_length=255)),
                ('patient_firstname', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('patient_left', models.BooleanField()),
                ('emotion', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
            ],
        ),
    ]
