# Generated by Django 4.2.3 on 2023-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppsy', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Le_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_lastname', models.CharField(max_length=255)),
                ('patient_firstname', models.CharField(max_length=255)),
                ('predicted', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
            ],
        ),
    ]
